# Use official Tomcat image
FROM tomcat:9.0

# Remove default web apps (optional but clean)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file into the Tomcat webapps directory
COPY target/VehicleMentananceAndService.war /usr/local/tomcat/webapps/ROOT.war

# Expose default Tomcat port
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]
